Python is a general-purpose programming language. When using Jupyter notebooks, we can use Python by writing one or more lines of code in a cell and executing it.

Python can do very simple operations, like basic arithmetic.

In [ ]:
1 + 5

In [ ]:
6 * 8

Exponentiation is done with two asterisks:

In [ ]:
5 ** 2

When we want to reuse a value, we can assign it to a variable. This is done using the equals sign.

In [ ]:
x = 3

Assignment lets you reuse those values across cells in the same notebook. Note that variables do not carry over from one notebook to another.

In [ ]:
5 * x

Assigning values makes it easy to quickly make changes to your calculations or experiment.

There are several basic types of objects in Python. We have numeric types, integers and floats.

In [ ]:
type(5)

In [ ]:
type(1.2)

We can also work with strings (text).

In [ ]:
type('hello')

We will often also work with Boolean (logical) values.

In [ ]:
type(True)

It is often useful to work with collections of objects. One basic type of collection is a list, which can hold zero or more objects.

In [ ]:
letters = ['a', 'b', 'c', 'd']

We and access elements of a list using indexing. Python, like many other programming languages, starts counting at 0.

In [ ]:
letters[1]

In [ ]:
letters[0]

In [ ]:
letters[-1]

In [ ]:
letters[1:3]

While lists are useful for holding multiple objects, they are not as good at doing calculations. For example, I can't just easily multiply each element of a list by a number.

In [ ]:
my_nums = [1, 2, 3]

In [ ]:
my_nums*2

The numpy **library** is useful for doing calculations on collections of numbers. Let's import this library and see what that looks like.

In [2]:
import numpy as np

In [3]:
my_nums = np.array([1, 2, 3])
my_nums

array([1, 2, 3])

In [4]:
my_nums*2

array([2, 4, 6])

In [5]:
my_nums**2

array([1, 4, 9])